/**
 * Supabase Auth Client - Production Ready
 * 
 * ============================================
 * IMPORTANT: CONFIGURATION REQUIRED
 * ============================================
 * 
 * Before using this file, you MUST update the configuration below:
 * 
 * 1. Go to your Supabase Dashboard: https://supabase.com/dashboard
 * 2. Select your project
 * 3. Go to Settings → API
 * 4. Copy your "Project URL" and "anon public" key
 * 5. Update SUPABASE_URL and SUPABASE_ANON_KEY below
 * 
 * SECURITY:
 * - Uses anon key only (safe to expose in client-side code)
 * - No secrets exposed to frontend
 * - RLS policies protect data access
 * - OAuth URLs are generated by Supabase SDK (not hardcoded)
 * - Session handled by Supabase automatically
 * 
 * USAGE:
 * 1. Include Supabase JS: <script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>
 * 2. Include this file: <script src="js/auth.js"></script>
 * 3. Auth initializes automatically on page load
 */

// ============================================
// CONFIGURATION - YOU MUST UPDATE THESE
// ============================================
// Get these from: Supabase Dashboard → Settings → API

const SUPABASE_URL = 'https://udoscezrjuuudhxvxzpp.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkb3NjZXpyanV1dWRoeHZ4enBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxOTkyNzEsImV4cCI6MjA4Mzc3NTI3MX0.3SqQqXHpXUH07va7ZEprNgzlEMeqPBp-_QBP8vxrcIM';

// Default redirect after successful login
const DEFAULT_REDIRECT = '/my-page.html';

// ============================================
// SUPABASE CLIENT INITIALIZATION
// ============================================
let supabaseClient = null;
let authInitialized = false;

/**
 * Validate that Supabase is properly configured
 * @returns {boolean} True if configured, false otherwise
 */
function isConfigured() {
    // Check if URL and Key are set and not placeholder values
    if (!SUPABASE_URL || SUPABASE_URL === '' || SUPABASE_URL.includes('YOUR_')) {
        return false;
    }
    if (!SUPABASE_ANON_KEY || SUPABASE_ANON_KEY === '' || SUPABASE_ANON_KEY.includes('YOUR_')) {
        return false;
    }
    // Basic URL validation
    if (!SUPABASE_URL.startsWith('https://') || !SUPABASE_URL.includes('.supabase.co')) {
        return false;
    }
    return true;
}

/**
 * Initialize and return the Supabase client (singleton pattern)
 * Uses the Supabase JS SDK - NO hardcoded OAuth URLs
 * @returns {Object|null} Supabase client instance
 */
function getSupabase() {
    // Return existing client if already initialized
    if (supabaseClient) {
        return supabaseClient;
    }

    // Check if Supabase JS library is loaded
    if (typeof window === 'undefined' || typeof window.supabase === 'undefined') {
        console.error('[Auth] ❌ Supabase JS library not loaded.');
        console.error('[Auth] Add this script tag to your HTML <head>:');
        console.error('    <script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>');
        return null;
    }

    // Validate configuration
    if (!isConfigured()) {
        console.warn('[Auth] ⚠️ Supabase not configured. Login features disabled.');
        console.warn('[Auth] To enable, update SUPABASE_URL and SUPABASE_ANON_KEY in js/auth.js');
        console.warn('[Auth] Get these from: Supabase Dashboard → Settings → API');
        return null;
    }

    try {
        // Create client using Supabase SDK
        // The SDK handles all OAuth URL generation internally - we never hardcode auth URLs
        supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
            auth: {
                autoRefreshToken: true,
                persistSession: true,
                detectSessionInUrl: true,  // Important for OAuth callback handling
            }
        });
        console.log('[Auth] ✅ Supabase client initialized');
        return supabaseClient;
    } catch (err) {
        console.error('[Auth] ❌ Failed to create Supabase client:', err.message);
        return null;
    }
}

// ============================================
// AUTHENTICATION FUNCTIONS
// ============================================

/**
 * Get the current authenticated user
 * Checks session stored by Supabase (persists across reloads)
 * @returns {Promise<Object|null>} User object or null if not authenticated
 */
async function getCurrentUser() {
    const supabase = getSupabase();
    if (!supabase) return null;

    try {
        const { data: { user }, error } = await supabase.auth.getUser();
        if (error) {
            // Don't log expected "not authenticated" errors
            if (!error.message.toLowerCase().includes('not authenticated') &&
                !error.message.toLowerCase().includes('session')) {
                console.error('[Auth] Error getting user:', error.message);
            }
            return null;
        }
        return user;
    } catch (err) {
        console.error('[Auth] Exception getting user:', err);
        return null;
    }
}

/**
 * Get the current session (includes access token)
 * @returns {Promise<Object|null>} Session object or null
 */
async function getSession() {
    const supabase = getSupabase();
    if (!supabase) return null;

    try {
        const { data: { session }, error } = await supabase.auth.getSession();
        if (error) {
            console.error('[Auth] Error getting session:', error.message);
            return null;
        }
        return session;
    } catch (err) {
        console.error('[Auth] Exception getting session:', err);
        return null;
    }
}

/**
 * Sign in with Google OAuth
 * 
 * IMPORTANT: This uses supabase.auth.signInWithOAuth which generates
 * the correct OAuth URL dynamically. We NEVER hardcode OAuth URLs.
 * 
 * Flow:
 * 1. Call this function
 * 2. Supabase SDK generates proper OAuth URL for your project
 * 3. User is redirected to Google for authentication
 * 4. Google redirects back to your site with auth tokens
 * 5. Supabase SDK handles the tokens automatically
 * 
 * @param {string} redirectTo - URL to redirect after successful login
 * @returns {Promise<{success: boolean, error?: string}>}
 */
async function loginWithGoogle(redirectTo) {
    const supabase = getSupabase();
    if (!supabase) {
        console.error('[Auth] Cannot login - Supabase not configured');
        alert('Login is not available. Please configure Supabase first.');
        return { success: false, error: 'Supabase not initialized' };
    }

    // Determine redirect URL
    const redirect = redirectTo || (window.location.origin + DEFAULT_REDIRECT);

    try {
        console.log('[Auth] Starting Google OAuth flow...');
        console.log('[Auth] Will redirect to:', redirect);

        // Use Supabase SDK to generate OAuth URL and redirect
        // The SDK handles everything - we don't hardcode any URLs
        const { data, error } = await supabase.auth.signInWithOAuth({
            provider: 'google',
            options: {
                redirectTo: redirect,
            },
        });

        if (error) {
            console.error('[Auth] ❌ Google OAuth error:', error.message);
            alert('Login failed: ' + error.message);
            return { success: false, error: error.message };
        }

        // data.url contains the OAuth URL generated by Supabase
        // The SDK will automatically redirect the user
        console.log('[Auth] ✅ OAuth initiated, redirecting to Google...');
        return { success: true };

    } catch (err) {
        console.error('[Auth] ❌ Exception during OAuth:', err);
        alert('Login failed. Please try again.');
        return { success: false, error: err.message };
    }
}

/**
 * Sign in using Magic Link (passwordless email)
 * @param {string} email - User email address
 * @param {string} redirectTo - URL to redirect after clicking Magic Link
 * @returns {Promise<{success: boolean, error?: string}>}
 */
async function signInWithEmail(email, redirectTo) {
    const supabase = getSupabase();
    if (!supabase) {
        return { success: false, error: 'Supabase not initialized' };
    }

    const redirect = redirectTo || (window.location.origin + DEFAULT_REDIRECT);

    try {
        console.log('[Auth] Sending Magic Link to:', email);
        const { error } = await supabase.auth.signInWithOtp({
            email,
            options: {
                emailRedirectTo: redirect,
            }
        });

        if (error) {
            console.error('[Auth] ❌ Magic Link error:', error.message);
            return { success: false, error: error.message };
        }

        console.log('[Auth] ✅ Magic Link sent successfully');
        return { success: true };
    } catch (err) {
        console.error('[Auth] ❌ Exception during Magic Link:', err);
        return { success: false, error: err.message };
    }
}

/**
 * Sign up a new user using Magic Link (passwordless email)
 * @param {string} email - User email address
 * @param {string} firstName - User's first name
 * @param {string} lastName - User's last name
 * @param {string} redirectTo - URL to redirect after clicking Magic Link
 * @returns {Promise<{success: boolean, error?: string}>}
 */
async function signUpWithEmail(email, firstName, lastName, redirectTo) {
    const supabase = getSupabase();
    if (!supabase) {
        return { success: false, error: 'Supabase not initialized' };
    }

    const redirect = redirectTo || (window.location.origin + DEFAULT_REDIRECT);

    try {
        console.log('[Auth] Signing up new user:', email);
        const { error } = await supabase.auth.signInWithOtp({
            email,
            options: {
                emailRedirectTo: redirect,
                data: {
                    first_name: firstName,
                    last_name: lastName,
                    full_name: `${firstName} ${lastName}`.trim()
                },
                shouldCreateUser: true
            }
        });

        if (error) {
            console.error('[Auth] ❌ Signup error:', error.message);
            return { success: false, error: error.message };
        }

        console.log('[Auth] ✅ Signup Magic Link sent successfully');
        return { success: true };
    } catch (err) {
        console.error('[Auth] ❌ Exception during Signup:', err);
        return { success: false, error: err.message };
    }
}

/**
 * Verify a 6-digit Email OTP code
 * @param {string} email - User email address
 * @param {string} token - The 6-digit OTP code
 * @param {string} type - OTP type ('signup' or 'email')
 * @returns {Promise<{success: boolean, error?: string, session?: Object}>}
 */
async function verifyOTP(email, token, type = 'email') {
    const supabase = getSupabase();
    if (!supabase) {
        return { success: false, error: 'Supabase not initialized' };
    }

    try {
        console.log(`[Auth] Verifying ${type} OTP for:`, email);
        const { data, error } = await supabase.auth.verifyOtp({
            email,
            token,
            type
        });

        if (error) {
            console.error('[Auth] ❌ OTP verification error:', error.message);
            return { success: false, error: error.message };
        }

        console.log('[Auth] ✅ OTP verified successfully');
        return { success: true, session: data.session };
    } catch (err) {
        console.error('[Auth] ❌ Exception during OTP verification:', err);
        return { success: false, error: err.message };
    }
}

// Alias for backwards compatibility
const signInWithGoogle = loginWithGoogle;

/**
 * Sign out the current user
 * @param {string} redirectTo - URL to redirect after sign out (default: home)
 * @returns {Promise<{success: boolean, error?: string}>}
 */
async function logout(redirectTo = '/') {
    const supabase = getSupabase();
    if (!supabase) {
        return { success: false, error: 'Supabase not initialized' };
    }

    try {
        console.log('[Auth] Signing out...');
        const { error } = await supabase.auth.signOut();

        if (error) {
            console.error('[Auth] Sign out error:', error.message);
            return { success: false, error: error.message };
        }

        console.log('[Auth] ✅ User signed out');

        // Redirect after logout
        if (redirectTo) {
            window.location.href = redirectTo;
        }

        return { success: true };
    } catch (err) {
        console.error('[Auth] Exception during sign out:', err);
        return { success: false, error: err.message };
    }
}

// Alias for backwards compatibility
const signOut = logout;

/**
 * Listen for auth state changes
 * @param {Function} callback - Called with (event, session) on auth changes
 * @returns {Function} Unsubscribe function
 */
function onAuthStateChange(callback) {
    const supabase = getSupabase();
    if (!supabase) return () => { };

    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
        console.log('[Auth] Auth state changed:', event);
        callback(event, session);
    });

    return () => subscription.unsubscribe();
}

// ============================================
// LOGIN MODAL
// ============================================

/**
 * Show the login modal popup
 */
function showLoginModal() {
    // Check if modal already exists
    let modal = document.getElementById('login-modal-overlay');
    if (modal) {
        modal.classList.add('active');
        return;
    }

    // Get translations
    const getTranslation = (key) => {
        const lang = window.currentLang || 'en';
        const t = window.translations?.[lang] || window.translations?.en || {};
        return t[key] || key;
    };

    // Create modal
    modal = document.createElement('div');
    modal.id = 'login-modal-overlay';
    modal.className = 'login-modal-overlay';
    modal.innerHTML = `
        <div class="login-modal-content">
            <button class="login-modal-close">&times;</button>
            
            <h2 class="login-modal-title" data-i18n="loginModal.title">ログイン / サインアップ</h2>
            
            <!-- Google Button -->
            <button class="social-login-btn google-btn" id="modal-google-btn">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M21.35 11.1h-9.17v2.73h6.51c-.33 3.81-3.5 5.44-6.5 5.44C8.36 19.27 5 16.25 5 12c0-4.1 3.2-7.27 7.2-7.27 3.09 0 4.9 1.97 4.9 1.97L19 4.72S16.56 2 12.1 2C6.42 2 2.03 6.8 2.03 12c0 5.05 4.13 10 10.22 10 5.35 0 9.25-3.67 9.25-9.09 0-1.15-.15-2.15-.15-2.15z"/>
                </svg>
                <span data-i18n="loginModal.google">Googleで続ける</span>
            </button>
            
            <div class="login-divider">
                <span data-i18n="loginModal.or">または</span>
            </div>
            
            <!-- Login Form -->
            <div id="login-form-section">
                <div class="login-input-group">
                    <input type="email" id="login-email" class="login-input" placeholder="メールアドレス" data-placeholder-i18n="loginModal.emailPlaceholder">
                </div>
                <button class="login-submit-btn" id="login-continue-btn" data-i18n="loginModal.continue">続ける</button>
            </div>
            
            <!-- Signup Form (hidden by default) -->
            <div id="signup-form-section" style="display: none;">
                <div class="login-input-row">
                    <div class="login-input-group">
                        <input type="text" id="signup-firstname" class="login-input" placeholder="名" data-placeholder-i18n="loginModal.firstName">
                    </div>
                    <div class="login-input-group">
                        <input type="text" id="signup-lastname" class="login-input" placeholder="姓" data-placeholder-i18n="loginModal.lastName">
                    </div>
                </div>
                <div class="login-input-group">
                    <input type="email" id="signup-email" class="login-input" placeholder="メールアドレス" data-placeholder-i18n="loginModal.emailPlaceholder">
                </div>
                <button class="login-submit-btn" id="signup-continue-btn" data-i18n="loginModal.signupBtn">サインアップ</button>
            </div>
            
            <!-- Toggle Login/Signup -->
            <div class="login-toggle-section" id="toggle-to-signup">
                <span data-i18n="loginModal.noAccount">アカウントをお持ちでない方は？</span>
                <a href="#" class="login-toggle-link" data-i18n="loginModal.signup">サインアップ</a>
            </div>
            <div class="login-toggle-section" id="toggle-to-login" style="display: none;">
                <span data-i18n="loginModal.hasAccount">すでにアカウントをお持ちの方は？</span>
                <a href="#" class="login-toggle-link" data-i18n="loginModal.login">ログイン</a>
            </div>
        </div>
    `;

    // Add styles
    const styleId = 'login-modal-styles';
    if (!document.getElementById(styleId)) {
        const style = document.createElement('style');
        style.id = styleId;
        style.textContent = `
            .login-modal-overlay {
                position: fixed;
                inset: 0;
                background: rgba(0,0,0,0.8);
                backdrop-filter: blur(8px);
                z-index: 10002;
                display: flex;
                align-items: center;
                justify-content: center;
                opacity: 0;
                visibility: hidden;
                transition: all 0.3s ease;
            }
            .login-modal-overlay.active {
                opacity: 1;
                visibility: visible;
            }
            .login-modal-content {
                background: #1a1a1a;
                border: 1px solid rgba(255,255,255,0.1);
                border-radius: 16px;
                padding: 2.5rem;
                width: 90%;
                max-width: 400px;
                position: relative;
                transform: translateY(-20px);
                transition: transform 0.3s ease;
            }
            .login-modal-overlay.active .login-modal-content {
                transform: translateY(0);
            }
            .login-modal-close {
                position: absolute;
                top: 1rem;
                right: 1rem;
                background: transparent;
                border: none;
                color: #888;
                font-size: 1.5rem;
                cursor: pointer;
                padding: 0.5rem;
                line-height: 1;
            }
            .login-modal-close:hover {
                color: #fff;
            }
            .login-modal-title {
                font-family: var(--font-display, 'Playfair Display', serif);
                font-size: 1.5rem;
                text-align: center;
                margin-bottom: 2rem;
                color: #fff;
            }
            .social-login-btn {
                width: 100%;
                display: flex;
                align-items: center;
                justify-content: center;
                gap: 0.75rem;
                padding: 0.9rem 1.5rem;
                border-radius: 8px;
                font-size: 1rem;
                cursor: pointer;
                transition: all 0.2s;
                border: 1px solid #333;
                background: #222;
                color: #fff;
            }
            .social-login-btn:hover {
                background: #333;
                border-color: #444;
            }
            .login-divider {
                position: relative;
                text-align: center;
                margin: 1.5rem 0;
                border-bottom: 1px solid #333;
                line-height: 0;
            }
            .login-divider span {
                background: #1a1a1a;
                padding: 0 1rem;
                color: #666;
                font-size: 0.85rem;
            }
            .login-input-group {
                margin-bottom: 1rem;
            }
            .login-input-row {
                display: flex;
                gap: 1rem;
            }
            .login-input-row .login-input-group {
                flex: 1;
            }
            .login-input {
                width: 100%;
                background: transparent;
                border: 1px solid #333;
                border-radius: 8px;
                padding: 0.9rem 1rem;
                color: #fff;
                font-size: 1rem;
                outline: none;
                transition: border-color 0.2s;
            }
            .login-input:focus {
                border-color: #fff;
            }
            .login-input::placeholder {
                color: #666;
            }
            .login-submit-btn {
                width: 100%;
                background: #fff;
                color: #000;
                border: none;
                padding: 0.9rem 1.5rem;
                border-radius: 8px;
                font-size: 1rem;
                font-weight: 600;
                cursor: pointer;
                transition: all 0.2s;
                margin-top: 0.5rem;
            }
            .login-submit-btn:hover {
                background: #e0e0e0;
            }
            .login-toggle-section {
                text-align: center;
                margin-top: 1.5rem;
                font-size: 0.9rem;
                color: #888;
            }
            .login-toggle-link {
                color: #fff;
                text-decoration: underline;
                margin-left: 0.5rem;
            }
            .login-toggle-link:hover {
                color: #ccc;
            }
        `;
        document.head.appendChild(style);
    }

    document.body.appendChild(modal);

    // Event handlers
    const closeModal = () => modal.classList.remove('active');

    modal.querySelector('.login-modal-close').addEventListener('click', closeModal);
    modal.addEventListener('click', (e) => {
        if (e.target === modal) closeModal();
    });

    // Google login
    modal.querySelector('#modal-google-btn').addEventListener('click', () => {
        closeModal();
        loginWithGoogle();
    });

    // Toggle to signup
    modal.querySelector('#toggle-to-signup .login-toggle-link').addEventListener('click', (e) => {
        e.preventDefault();
        document.getElementById('login-form-section').style.display = 'none';
        document.getElementById('signup-form-section').style.display = 'block';
        document.getElementById('toggle-to-signup').style.display = 'none';
        document.getElementById('toggle-to-login').style.display = 'block';
    });

    // Toggle to login
    modal.querySelector('#toggle-to-login .login-toggle-link').addEventListener('click', (e) => {
        e.preventDefault();
        document.getElementById('login-form-section').style.display = 'block';
        document.getElementById('signup-form-section').style.display = 'none';
        document.getElementById('toggle-to-signup').style.display = 'block';
        document.getElementById('toggle-to-login').style.display = 'none';
    });

    // Email login button
    modal.querySelector('#login-continue-btn').addEventListener('click', async (e) => {
        const emailInput = document.getElementById('login-email');
        const email = emailInput ? emailInput.value : '';
        const btn = e.currentTarget;

        if (!email) {
            alert('Please enter your email address.');
            return;
        }

        btn.disabled = true;
        const originalText = btn.textContent;
        btn.textContent = window.currentLang === 'jp' ? '送信中...' : 'Sending...';

        const result = await signInWithEmail(email);

        if (result.success) {
            showOtpState(email, 'email');
        } else {
            alert('Error: ' + result.error);
            btn.disabled = false;
            btn.textContent = originalText;
        }
    });

    // Signup button
    modal.querySelector('#signup-continue-btn').addEventListener('click', async (e) => {
        const firstNameEl = document.getElementById('signup-firstname');
        const lastNameEl = document.getElementById('signup-lastname');
        const emailEl = document.getElementById('signup-email');

        const firstName = firstNameEl ? firstNameEl.value : '';
        const lastName = lastNameEl ? lastNameEl.value : '';
        const email = emailEl ? emailEl.value : '';
        const btn = e.currentTarget;

        if (!firstName || !lastName || !email) {
            alert('Please fill in all fields.');
            return;
        }

        btn.disabled = true;
        const originalText = btn.textContent;
        btn.textContent = window.currentLang === 'jp' ? '送信中...' : 'Sending...';

        const result = await signUpWithEmail(email, firstName, lastName);

        if (result.success) {
            showOtpState(email, 'signup');
        } else {
            alert('Error: ' + result.error);
            btn.disabled = false;
            btn.textContent = originalText;
        }
    });

    /**
     * Show OTP entry state in the modal
     * @param {string} email - The email to verify
     * @param {string} type - 'email' for login, 'signup' for new user
     */
    function showOtpState(email, type = 'email') {
        const isJP = window.currentLang === 'jp';
        const content = modal.querySelector('.login-modal-content');
        if (!content) return;

        content.innerHTML = `
            <button class="login-modal-close">&times;</button>
            <div style="text-align: center; padding: 1rem 0;">
                <div style="font-size: 3rem; margin-bottom: 1.5rem;">🔢</div>
                <h2 class="login-modal-title" style="margin-bottom: 1rem;">${isJP ? '確認コードを入力' : 'Enter Verification Code'}</h2>
                <p style="color: #aaa; margin-bottom: 2rem; line-height: 1.6;">
                    ${isJP
                ? `<strong>${email}</strong> 宛に送信された6桁の確認コードを入力してください。`
                : `Please enter the 6-digit verification code sent to <strong>${email}</strong>.`}
                </p>
                <div class="login-input-group">
                    <input type="text" id="modal-otp-input" class="login-input" placeholder="000000" maxlength="6" style="text-align: center; font-size: 1.5rem; letter-spacing: 0.5rem; font-weight: bold;">
                </div>
                <button class="login-submit-btn" id="modal-verify-btn">${isJP ? '確認する' : 'Verify'}</button>
                <div class="login-toggle-section">
                    <a href="#" class="login-toggle-link" id="modal-otp-back">${isJP ? '戻る' : 'Back'}</a>
                </div>
            </div>
        `;

        // Re-bind close button
        content.querySelector('.login-modal-close').addEventListener('click', closeModal);

        const verifyBtn = content.querySelector('#modal-verify-btn');
        const otpInput = content.querySelector('#modal-otp-input');
        const backLink = content.querySelector('#modal-otp-back');

        backLink.addEventListener('click', (e) => {
            e.preventDefault();
            // Re-render the initial modal state or just close and let them re-open
            // For simplicity, let's just close for now, or we could store the initial HTML
            closeModal();
        });

        verifyBtn.addEventListener('click', async () => {
            const token = otpInput.value.trim();
            if (token.length !== 6) {
                alert(isJP ? '6桁のコードを入力してください。' : 'Please enter a 6-digit code.');
                return;
            }

            verifyBtn.disabled = true;
            const originalText = verifyBtn.textContent;
            verifyBtn.textContent = isJP ? '検証中...' : 'Verifying...';

            const result = await verifyOTP(email, token, type);

            if (result.success) {
                content.innerHTML = `
                    <button class="login-modal-close">&times;</button>
                    <div style="text-align: center; padding: 1rem 0;">
                        <div style="font-size: 3rem; margin-bottom: 1.5rem;">🎉</div>
                        <h2 class="login-modal-title" style="margin-bottom: 1rem;">${isJP ? '認証成功' : 'Verified!'}</h2>
                        <p style="color: #aaa; margin-bottom: 2rem;">
                            ${isJP ? 'ログインが完了しました。' : 'You have been successfully signed in.'}
                        </p>
                        <button class="login-submit-btn" id="success-done-btn">${isJP ? '完了' : 'Done'}</button>
                    </div>
                `;
                content.querySelector('.login-modal-close').addEventListener('click', () => {
                    closeModal();
                    location.reload();
                });
                content.querySelector('#success-done-btn').addEventListener('click', () => {
                    closeModal();
                    location.reload();
                });
            } else {
                alert('Error: ' + result.error);
                verifyBtn.disabled = false;
                verifyBtn.textContent = originalText;
            }
        });

        // Focus input
        otpInput.focus();
    }

    // Apply translations if available
    if (window.updateContent) {
        window.updateContent();
    }

    // Show modal
    setTimeout(() => modal.classList.add('active'), 10);
}

/**
 * Hide the login modal
 */
function hideLoginModal() {
    const modal = document.getElementById('login-modal-overlay');
    if (modal) {
        modal.classList.remove('active');
    }
}

// ============================================
// UI UPDATE FUNCTIONS
// ============================================

/**
 * Bind click handlers to login buttons
 * This is called even when Supabase is not configured (to show an alert)
 */
function bindLoginHandlers() {
    const loginBtn = document.querySelector('.btn-login');
    const mobileLoginBtn = document.querySelector('.mobile-login');

    // Handler that triggers Google OAuth or shows alert if not configured
    const handleLoginClick = (e) => {
        e.preventDefault();
        loginWithGoogle();  // This will show alert if not configured
    };

    if (loginBtn) {
        loginBtn.href = '#';
        loginBtn.onclick = handleLoginClick;
    }

    if (mobileLoginBtn) {
        mobileLoginBtn.href = '#';
        mobileLoginBtn.onclick = (e) => {
            e.preventDefault();
            if (typeof closeMenu === 'function') {
                closeMenu();
            }
            loginWithGoogle();
        };
    }
}

/**
 * Update header buttons based on auth state
 * 
 * If logged out:
 *   - "Login" button triggers Google OAuth
 * 
 * If logged in:
 *   - "My Page" button links to /my-page.html
 */
async function updateAuthUI() {
    const user = await getCurrentUser();

    // Find header buttons
    const loginBtn = document.querySelector('.btn-login');
    const mobileLoginBtn = document.querySelector('.mobile-login');

    // Get translated text based on current language
    const getTranslation = (key) => {
        const lang = window.currentLang || 'en';
        const t = window.translations?.[lang] || window.translations?.en || {};
        return t[key] || key;
    };

    // Create or get the account dropdown
    const createAccountDropdown = () => {
        let dropdown = document.getElementById('account-dropdown');
        if (!dropdown) {
            dropdown = document.createElement('div');
            dropdown.id = 'account-dropdown';
            dropdown.className = 'account-dropdown';
            dropdown.innerHTML = `
                <div class="dropdown-content">
                    <a href="/my-page.html" class="dropdown-item" data-i18n="dropdown.mypage">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/>
                            <circle cx="12" cy="7" r="4"/>
                        </svg>
                        My Page
                    </a>
                    <button class="dropdown-item" id="switch-account-btn" data-i18n="dropdown.switch">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/>
                            <circle cx="8.5" cy="7" r="4"/>
                            <path d="M20 8v6"/>
                            <path d="M23 11l-3-3-3 3"/>
                        </svg>
                        Switch Account
                    </button>
                    <button class="dropdown-item dropdown-signout" id="signout-btn" data-i18n="dropdown.signout">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/>
                            <polyline points="16,17 21,12 16,7"/>
                            <line x1="21" y1="12" x2="9" y2="12"/>
                        </svg>
                        Sign Out
                    </button>
                </div>
            `;
            document.body.appendChild(dropdown);

            // Add event listeners
            dropdown.querySelector('#signout-btn').addEventListener('click', async () => {
                dropdown.classList.remove('active');
                await logout();
                window.location.href = '/';
            });

            dropdown.querySelector('#switch-account-btn').addEventListener('click', async () => {
                dropdown.classList.remove('active');
                await logout();
                // Re-login with Google (will show account picker)
                loginWithGoogle();
            });

            // Close dropdown when clicking outside
            document.addEventListener('click', (e) => {
                if (!dropdown.contains(e.target) && !e.target.closest('.btn-login')) {
                    dropdown.classList.remove('active');
                }
            });
        }
        return dropdown;
    };

    // Add dropdown CSS if not present
    const addDropdownStyles = () => {
        if (document.getElementById('account-dropdown-styles')) return;

        const style = document.createElement('style');
        style.id = 'account-dropdown-styles';
        style.textContent = `
            .account-dropdown {
                position: fixed;
                top: 70px;
                right: 20px;
                z-index: 10001;
                opacity: 0;
                visibility: hidden;
                transform: translateY(-10px);
                transition: all 0.2s ease;
            }
            .account-dropdown.active {
                opacity: 1;
                visibility: visible;
                transform: translateY(0);
            }
            .dropdown-content {
                background: #1a1a1a;
                border: 1px solid rgba(255,255,255,0.1);
                border-radius: 12px;
                padding: 0.5rem;
                min-width: 200px;
                box-shadow: 0 10px 40px rgba(0,0,0,0.4);
            }
            .dropdown-item {
                display: flex;
                align-items: center;
                gap: 10px;
                width: 100%;
                padding: 0.75rem 1rem;
                background: transparent;
                border: none;
                color: #fff;
                font-size: 0.9rem;
                cursor: pointer;
                border-radius: 8px;
                transition: background 0.2s;
                text-decoration: none;
            }
            .dropdown-item:hover {
                background: rgba(255,255,255,0.1);
            }
            .dropdown-item svg {
                opacity: 0.7;
            }
            .dropdown-signout {
                color: #ff6b6b;
            }
            .dropdown-signout:hover {
                background: rgba(255,107,107,0.1);
            }
        `;
        document.head.appendChild(style);
    };

    if (user) {
        // ========== USER IS LOGGED IN ==========
        console.log('[Auth] UI: User logged in as', user.email);

        const myPageText = getTranslation('nav.mypage');
        addDropdownStyles();
        const dropdown = createAccountDropdown();

        if (loginBtn) {
            loginBtn.textContent = myPageText;
            loginBtn.setAttribute('data-i18n', 'nav.mypage');
            loginBtn.href = '#';
            loginBtn.onclick = (e) => {
                e.preventDefault();
                e.stopPropagation();
                // Position dropdown near the button
                const rect = loginBtn.getBoundingClientRect();
                dropdown.style.top = (rect.bottom + 10) + 'px';
                dropdown.style.right = (window.innerWidth - rect.right) + 'px';
                dropdown.classList.toggle('active');
            };
        }

        if (mobileLoginBtn) {
            mobileLoginBtn.textContent = myPageText;
            mobileLoginBtn.setAttribute('data-i18n', 'nav.mypage');
            mobileLoginBtn.href = '/my-page.html';
            mobileLoginBtn.onclick = null;  // Let mobile link work normally
        }

    } else {
        // ========== USER IS LOGGED OUT ==========
        console.log('[Auth] UI: No user logged in');

        // Remove dropdown if exists
        const existingDropdown = document.getElementById('account-dropdown');
        if (existingDropdown) {
            existingDropdown.remove();
        }

        const loginText = getTranslation('nav.login');

        if (loginBtn) {
            loginBtn.textContent = loginText;
            loginBtn.setAttribute('data-i18n', 'nav.login');
            loginBtn.href = '#';
            loginBtn.onclick = (e) => {
                e.preventDefault();
                showLoginModal();
            };
        }

        if (mobileLoginBtn) {
            mobileLoginBtn.textContent = loginText;
            mobileLoginBtn.setAttribute('data-i18n', 'nav.login');
            mobileLoginBtn.href = '#';
            mobileLoginBtn.onclick = (e) => {
                e.preventDefault();
                // Close mobile menu if function exists
                if (typeof closeMenu === 'function') {
                    closeMenu();
                }
                showLoginModal();
            };
        }
    }
}

/**
 * Initialize authentication on page load
 * This is called automatically when the script loads
 */
async function initAuth() {
    // Prevent double initialization
    if (authInitialized) return;
    authInitialized = true;

    console.log('[Auth] Initializing...');

    // Always bind UI handlers (even if not configured, to show alert)
    bindLoginHandlers();

    // Check configuration
    if (!isConfigured()) {
        console.warn('[Auth] ⚠️ Auth disabled - Supabase not configured');
        console.warn('[Auth] Update SUPABASE_URL and SUPABASE_ANON_KEY in js/auth.js');
        return;
    }

    // Initialize client
    const supabase = getSupabase();
    if (!supabase) {
        console.warn('[Auth] ⚠️ Auth disabled - client initialization failed');
        return;
    }

    // Update UI based on current auth state
    await updateAuthUI();

    // Listen for auth state changes (handles returning from OAuth)
    onAuthStateChange(async (event, session) => {
        console.log('[Auth] State change event:', event);

        if (event === 'SIGNED_IN') {
            console.log('[Auth] ✅ User signed in');
            await updateAuthUI();
        } else if (event === 'SIGNED_OUT') {
            console.log('[Auth] User signed out');
            await updateAuthUI();
        } else if (event === 'TOKEN_REFRESHED') {
            console.log('[Auth] Token refreshed');
        }
    });

    console.log('[Auth] ✅ Initialization complete');
}

// ============================================
// RESERVATION FUNCTIONS
// ============================================

/**
 * Link a Stripe reservation to the current user
 */
async function linkReservationToUser(sessionId) {
    const session = await getSession();
    if (!session) {
        return { success: false, error: 'Not authenticated' };
    }

    try {
        const response = await fetch('/api/reservations/link', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${session.access_token}`,
            },
            body: JSON.stringify({ sessionId }),
        });

        const data = await response.json();
        return response.ok ? { success: true } : { success: false, error: data.error };
    } catch (err) {
        console.error('[Auth] Error linking reservation:', err);
        return { success: false, error: err.message };
    }
}

/**
 * Get current user's reservations
 */
async function getMyReservations() {
    const session = await getSession();
    if (!session) return [];

    try {
        const response = await fetch('/api/reservations/my', {
            headers: {
                'Authorization': `Bearer ${session.access_token}`,
            },
        });

        const data = await response.json();
        return response.ok ? (data.reservations || []) : [];
    } catch (err) {
        console.error('[Auth] Error fetching reservations:', err);
        return [];
    }
}

// ============================================
// AUTO-INITIALIZATION
// ============================================

// Initialize auth when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initAuth);
} else {
    // DOM already loaded - initialize immediately
    initAuth();
}

// ============================================
// GLOBAL EXPORTS
// ============================================

// Export all functions for use in other scripts
window.SupabaseAuth = {
    // Configuration
    isConfigured,

    // Client
    getSupabase,

    // Auth state
    getCurrentUser,
    getSession,

    // Auth actions (new names)
    loginWithGoogle,
    signInWithEmail,
    signUpWithEmail,
    verifyOTP,
    logout,

    // Auth actions (backwards compatible)
    signInWithGoogle,
    signOut,

    // Listeners
    onAuthStateChange,

    // UI
    updateAuthUI,
    initAuth,

    // Reservations
    linkReservationToUser,
    getMyReservations,
};

// Also export standalone functions for direct use
window.loginWithGoogle = loginWithGoogle;
window.logout = logout;
